# QUIC is not yet compiled by default for Nginx
# listen 443 quic reuseport;
# listen [::]:443 quic reuseport;

listen 443 ssl;
listen [::]:443 ssl;

# This is not supported on Nginx 1.18, which comes with Ubuntu 22.04
http2 on;
