# The reuseport option can be set for only one server, and is then applied automatically for all others.
# It's therefore not configured here.
listen 443 ssl;
listen [::]:443 ssl;

# QUIC is available in Nginx 1.25.0 and later
listen 443 quic;
listen [::]:443 quic;
quic_retry on;

# This is not supported on Nginx 1.18, which comes with Ubuntu 22.04
http2 on;

http3 on;
http3_hq on;
